### PR TITLE
OC-90 Add spellchecking capability

### PR DESCRIPTION
**Pull request by amake**
This PR adds spellchecking capability by embedding LanguageTool. See Edit > Spellcheck after opening an XLIFF file.

Notable incidental changes:

- Java 8 is now required (required by LanguageTool)
- Jackson was updated for Java 8 compatibility
- bf3514ac2f8a2998ba4b6a4b6d62179df5a8ec2c It is now possible to distinguish between target text editing via free text edit vs e.g. search-and-replace
- 0c1794f5201ba93a669bbaf0d2b3913fb8c3047b & 74f1cd53816abe0c26530ebd1d2e9a320643d7bf Automated replacements (find-and-replace, spellcheck fixes) only take effect if the text to be replaced matches expectations
  - I forget why this was necessary; there must have been a corner case where the result of one replacement would change the text to be replaced by a subsequent replacement within a single batch operation.
- Bug fixes:
  - 72c514af3f577fd6b7902841ae442f8847ecb153 Incorrect `Locale` constructor used by `FindAndReplaceController`
  - b90346e4a16936ebc4bae78bb8c8cc1476b29432 Bad iteration order caused multiple replacements in same atom to be incorrect
  - 38c6126306faedb025d36a9dfdf4b3950575a46d Wrong row selected on LQI modification event

### CODE REVIEW

**Comment by philr-vistatec** [comment]
Thanks Aaron.

Phil

**Comment by tingley** [comment]
Minor issue: If I run spellcheck with no document open, I get "An error has occurred during spellcheck" or something similar.  The option should probably be greyed out.

**Comment by tingley** [comment]
I went very light on the functional testing, given that it's been out with users for quite a while.  Code looks fine; I noted one small issue above.

**Comment by amake** [comment]
@tingley Thanks for the check. I'll address the issue you mentioned soon, hopefully tonight.

**Pull request merged**
